#!/bin/bash

synapse_postgres_pass=$(openssl rand -hex 24)
registration_shared_secret=$(openssl rand -hex 24)
macaroon_secret_key=$(openssl rand -hex 24)


# Save the passwords
cat > /root/.matrix-secrets <<EOF
synapse_postgres_pass="${synapse_postgres_pass}"
registration_shared_secret="${registration_shared_secret}"
macaroon_secret_key="${macaroon_secret_key}"
EOF

# POSTGRES
sudo -u postgres -c "ALTER USER postgres PASSWORD '$synapse_postgres_pass';"

# MATRIX
# TODO: fill in homeserver.yaml passwords
sed "s/POSTGRES_PASSWORD/$synapse_postgres_pass/g" -i /etc/matrix-synapse/homeserver.yaml
sed "s/REGISTRATION_SHARED_SECRET/$registration_shared_secret/g" -i /etc/matrix-synapse/homeserver.yaml
sed "s/MACAROON_SECRET_KEY/$macaroon_secret_key/g" -i /etc/matrix-synapse/homeserver.yaml

systemctl start matrix-synapse
systemctl enable matrix-synapse

myip=$(hostname -I | awk '{print$1}')
sed -e "s|server_name localhost|servername ${myip}|g" \
    -i /etc/nginx/sites-available/00-digitalocean

systemctl restart nginx

# Remove the ssh force logout command
sed -e '/Match User root/d' \
    -e '/.*ForceCommand.*droplet.*/d' \
    -i /etc/ssh/sshd_config

systemctl restart ssh
