#!/bin/sh
#
# reset a matrix user password

random_pass="$(openssl rand -hex 20)"
printf "Username to reset (@username:example.com)\n"
read username

if echo "$username" | grep -Eq '^@.+:.+'; then
    printf "Setting password for $username to $random_pass\n"
    hashed_pass="$(hash_password -p $random_pass)"
    sudo -u postgres psql -c "UPDATE users SET password_hash='$hashed_pass' WHERE name='$username';"
else
    printf "Username must match format: @username:example.com\n"
    exit 1
fi
