#!/bin/sh

ELEMENT_VERSION=$1

if [ -z "$1" ]; then
    printf "Please specify the element version to download\n"
fi

cd /opt
wget "https://github.com/vector-im/element-web/releases/download/v$ELEMENT_VERSION/element-v$ELEMENT_VERSION.tar.gz"
tar -zxvf "element-v$ELEMENT_VERSION.tar.gz"
cp element/config.json "element-v$ELEMENT_VERSION"
ln -sf "element-v$ELEMENT_VERSION" element
rm /opt/element-*.tar.gz
