#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF

********************************************************************************

Welcome to DigitalOcean's 1-Click Matrix Droplet.

To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (HTTP), 443 (HTTPS), and 8448 (Matrix)

You will find a suite of useful utilities in your home directory.

Please run ./finish-setup to complete your Matrix installation!

********************************************************************************

To delete this message of the day: rm $(readlink -f ${0})
EOF
